config/routes.rb
Rails.application.routes.draw do
  resources :lesson_subjects

  resources :lessons
  resources :instructors
  resources :subjects
  resources :users


  root 'home#index'

  get 'users/index'

  get 'home/index'

  get 'users/new'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/courses', 		to: 'lessons#index'

  get '/instructors', 	to: 'instructors#index'

  get '/subjects', 		to: 'subjects#index'

  get 'enrollments/index'

  get 'enrollments/new'

  get 'enrollments/create'

  post 'enrollments/create'

  get 'search/index'

  get 'result/index'

  get 'subject/index'

  get 'course/index'

  get 'instructor/index'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/search.rb
class Search < ApplicationRecord
	has_many :subjects
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index

    if logged_in?

      @lessons = Lesson.all
      if !params[:subject].blank? && params[:search].blank?
        @lessons = Subject.find(params[:subject]).lessons
      elsif !params[:search].blank? && params[:subject].blank?
        @lessons = @lessons.search(params[:search]).order(:name)
      elsif !params[:subject].blank? && !params[:search].blank?
        @lessons = Subject.find(params[:subject]).lessons
        @lessons = @lessons.search(params[:search]).order(:name)
      else
        @lessons
      end

      @subjects = Subject.all.order(:name)

      @enrollment = Enrollment.create

      respond_to do |format|
        format.html
        format.js
      end

    else
      redirect_to root_url, notice: 'LOGIN OR SIGNUP TO CONTINUE'
    end

  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
    # @subjects = Subject.all
    # @search = Search.new
  end

  def search
  end

  # GET /lessons/new
  def new
  end

end

app/helpers/search_helper.rb
module SearchHelper

	def get_sub_list(subjects)
	  my_courses = current_user().courses		
      if my_courses.length == 0
        return "Not registered for courses"
      end
      str = "<li>#{my_courses[0].name}</li> "
      # puts "*******#{my_courses[0]}"
	  count = 1
      while count < my_courses.length do
      	str+="<li>#{my_courses[count].name}</li>"
        count+=1;
      end
      str.html_safe
  	end

	def get_subject_list(subjects)
	  str = "['Mathematics', 'Mathematics'], ['COSI', 'COSI']"
      str.html_safe
  	end

end

app/views/search/_form.html.erb
<%= form_for(search_path) do |f| %>

	<div class="control-group">
		<%= f.label :subject, class: 'control-group' %>
		<div class="controls">
			<%= collection_select( :subject, :official_id, Subject.all, :id, :name, {}, { :multiple => false}) %>
		</div>
	</div>


	<div class="control-group">
		<%= f.label "Course Name", class: 'control-label' %>
		<div class="controls">
			<%= text_field_tag :search, params[:search] %>
		</div>
	</div>


	<div class="control-group">
		<div class="controls">
			<%= f.submit 'Submit', class: 'btn btn-default' %>
		</div>
	</div>

<% end %>

app/views/search/_results.html.erb
<% if @lessons.blank? %>
  No Results Found.
<% else %>
  <table>
    <thead>
      <tr>
        <th>Name </th>
        <th>Code</th>
        <th>Independent Study</th>
        <th></th>
        <th>Requirements</th>
        <th colspan="4"></th>
      </tr>
    </thead>
    <tbody>
	  <% @lessons = @lessons.uniq %>
	  <% @lessons.each do |lesson| %>
	    <tr>
	      <td><%= lesson.name %></td>
	      <td><%= lesson.code %></td>
	      <td><%= lesson.independent_study %></td>
	      <td></td>
	      <td><%= lesson.requirements %></td>
	      <% if !Enrollment.where(user_id: current_user.id, lesson_id: lesson.id).exists? %>
		      <td><%= form_for(:enrollments, :url => url_for(:controller => "enrollments", :action => "create", :id => @enrollments)) do |f|%>
		     	<%= f.hidden_field :user_id, value: current_user.id %>
		      	<%= f.hidden_field :lesson_id, value: lesson.id %>
		       	<button type="submit" class="btn btn-primary"> Enroll</button>
	 		  <% end %>
			  </td>
		  <% else %>
			<td> Enrolled </td>
		  <% end %>
	    </tr>
	  <% end %>
	</tbody>
  </table>
<% end %>

app/views/search/index.html.erb
<h1> Search </h1>

<div class="search-box">
	  <%= form_tag(search_index_path, :method => "get", id: "search-form", remote: true) do %>
	    
	    <%= select_tag :subject, options_from_collection_for_select(@subjects, "id", "name"), placeholder: "Select Subject", include_blank: true, class: "form-control", onkeyup: "$('#search-form').submit();"%>
	    
	    <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search Courses", onkeyup: "$('#search-form').submit();" %>	  
	  <% end %>
</div>

<div id = "results">
  <%= render "results" %>
</div>

<!-- onekeyup? -->

app/views/search/index.js.erb
$("#results").html("<%= escape_javascript(render("results")) %>");

app/views/search/show.html.erb
<p id="notice"><%= notice %></p>