config/routes.rb
Rails.application.routes.draw do
  resources :lesson_subjects

  resources :lessons
  resources :instructors
  resources :subjects
  resources :users


  root 'home#index'

  get 'users/index'

  get 'home/index'

  get 'users/new'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/courses', 		to: 'lessons#index'

  get '/instructors', 	to: 'instructors#index'

  get '/subjects', 		to: 'subjects#index'

  get 'enrollments/index'

  get 'enrollments/new'

  get 'enrollments/create'

  post 'enrollments/create'

  get 'search/index'

  get 'result/index'

  get 'subject/index'

  get 'course/index'

  get 'instructor/index'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/instructor.rb
class Instructor < ApplicationRecord
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :set_instructor, only: [:show, :edit, :update, :destroy]

  # GET /instructors
  # GET /instructors.json
  def index
    if logged_in?
      @instructors = Instructor.all
    else
      redirect_to root_url, notice: 'LOGIN OR SIGNUP TO CONTINUE'
    end
  end

  # GET /instructors/1
  # GET /instructors/1.json
  def show
  end

  # GET /instructors/new
  def new
    @instructor = Instructor.new
  end


  # POST /instructors
  # POST /instructors.json
  def create
    @instructor = Instructor.new(instructor_params)

    respond_to do |format|
      if @instructor.save
        format.html { redirect_to @instructor, notice: 'Instructor was successfully created.' }
        format.json { render :show, status: :created, location: @instructor }
      else
        format.html { render :new }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instructor
      @instructor = Instructor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instructor_params
      params.require(:instructor).permit(:first_name, :last_name, :official_id, :comment, :email)
    end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/_form.html.erb
<%= form_for(instructor) do |f| %>
  <% if instructor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(instructor.errors.count, "error") %> prohibited this instructor from being saved:</h2>

      <ul>
      <% instructor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :official_id %>
    <%= f.number_field :official_id %>
  </div>

  <div class="field">
    <%= f.label :comment %>
    <%= f.text_field :comment %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/instructors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Instructors</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instructors.each do |instructor| %>
      <tr>
        <td><%= instructor.first_name %></td>
        <td><%= instructor.last_name %></td>
        <td><%= instructor.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/instructors/new.html.erb
<h1>New Instructor</h1>

<%= render 'form', instructor: @instructor %>

<%= link_to 'Back', instructors_path %>

app/views/instructors/show.html.erb
<%= render 'layouts/header' %>
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @instructor.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @instructor.last_name %>
</p>

<p>
  <strong>Official:</strong>
  <%= @instructor.official_id %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @instructor.comment %>
</p>

<p>
  <strong>Email:</strong>
  <%= @instructor.email %>
</p>

<%= link_to 'Edit', edit_instructor_path(@instructor) %> |
<%= link_to 'Back', instructors_path %>