config/routes.rb
Rails.application.routes.draw do
  resources :lesson_subjects

  resources :lessons
  resources :instructors
  resources :subjects
  resources :users


  root 'home#index'

  get 'users/index'

  get 'home/index'

  get 'users/new'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/courses', 		to: 'lessons#index'

  get '/instructors', 	to: 'instructors#index'

  get '/subjects', 		to: 'subjects#index'

  get 'enrollments/index'

  get 'enrollments/new'

  get 'enrollments/create'

  post 'enrollments/create'

  get 'search/index'

  get 'result/index'

  get 'subject/index'

  get 'course/index'

  get 'instructor/index'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/lesson.rb
class Lesson < ApplicationRecord

  has_many :enrollments
  has_many :users, through: :enrollments

  has_many :lesson_subjects
  has_many :subjects, through: :lesson_subjects

  def self.search(search)
	Lesson.where(Lesson.arel_table[:name].matches("%#{search}%"))
	#where("name ILIKE ?", "%#{search}%")
  end

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]

  # GET /lessons
  # GET /lessons.json
  def index

    if logged_in?
      @lessons = Lesson.all
    else
      redirect_to root_url, notice: 'LOGIN OR SIGNUP TO CONTINUE'
    end
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
  end

  # GET /lessons/new
  def new
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.erb
<%= form_for(lesson) do |f| %>
  <% if lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
      <% lesson.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :official_id %>
    <%= f.number_field :official_id %>
  </div>

  <div class="field">
    <%= f.label :comment %>
    <%= f.text_field :comment %>
  </div>

  <div class="field">
    <%= f.label :term %>
    <%= f.number_field :term %>
  </div>

  <div class="field">
    <%= f.label :code %>
    <%= f.text_field :code %>
  </div>

  <div class="field">
    <%= f.label :subjects %>
    <%= f.text_field :subjects %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lessons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th> Description </th>
    </tr>
  </thead>

  <tbody>
    <% @lessons.each do |lesson| %>
      <tr>
        <td><%= lesson.name %></td>
        <td><%= lesson.code %></td>
        <td><%= lesson.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/lessons/new.html.erb
<h1>New Lesson</h1>

<%= render 'form', lesson: @lesson %>

<%= link_to 'Back', lessons_path %>

app/views/lessons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @lesson.name %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @lesson.comment %>
</p>

<p>
  <strong>Term:</strong>
  <%= @lesson.term %>
</p>

<p>
  <strong>Code:</strong>
  <%= @lesson.code %>
</p>

<p>
  <strong>Subjects:</strong>
  <%= @lesson.subjects %>
</p>

<p>
  <strong>Description:</strong>
  <%= @lesson.description %>
</p>

<%= link_to 'Edit', edit_lesson_path(@lesson) %> |
<%= link_to 'Back', lessons_path %>