config/routes.rb
Rails.application.routes.draw do
  resources :lesson_subjects

  resources :lessons
  resources :instructors
  resources :subjects
  resources :users


  root 'home#index'

  get 'users/index'

  get 'home/index'

  get 'users/new'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/courses', 		to: 'lessons#index'

  get '/instructors', 	to: 'instructors#index'

  get '/subjects', 		to: 'subjects#index'

  get 'enrollments/index'

  get 'enrollments/new'

  get 'enrollments/create'

  post 'enrollments/create'

  get 'search/index'

  get 'result/index'

  get 'subject/index'

  get 'course/index'

  get 'instructor/index'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
	belongs_to :user
	belongs_to :lesson
end

app/models/instructor.rb
class Instructor < ApplicationRecord
end

app/models/lesson.rb
class Lesson < ApplicationRecord

  has_many :enrollments
  has_many :users, through: :enrollments

  has_many :lesson_subjects
  has_many :subjects, through: :lesson_subjects

  def self.search(search)
	Lesson.where(Lesson.arel_table[:name].matches("%#{search}%"))
	#where("name ILIKE ?", "%#{search}%")
  end

end

app/models/lesson_subject.rb
class LessonSubject < ApplicationRecord

  belongs_to :lesson
  belongs_to :subject
end

app/models/search.rb
class Search < ApplicationRecord
	has_many :subjects
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :lesson_subjects
  has_many :lessons, through: :lesson_subjects
end

app/models/user.rb
class User < ApplicationRecord

  attr_accessor :remember_token

  has_many :enrollments
  has_many :lessons, through: :enrollments

  before_save { email.downcase! }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index

    if logged_in?

      @lessons = Lesson.all
      if !params[:subject].blank? && params[:search].blank?
        @lessons = Subject.find(params[:subject]).lessons
      elsif !params[:search].blank? && params[:subject].blank?
        @lessons = @lessons.search(params[:search]).order(:name)
      elsif !params[:subject].blank? && !params[:search].blank?
        @lessons = Subject.find(params[:subject]).lessons
        @lessons = @lessons.search(params[:search]).order(:name)
      else
        @lessons
      end

      @subjects = Subject.all.order(:name)

      @enrollment = Enrollment.create

      respond_to do |format|
        format.html
        format.js
      end

    else
      redirect_to root_url, notice: 'LOGIN OR SIGNUP TO CONTINUE'
    end

  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
    # @subjects = Subject.all
    # @search = Search.new
  end

  def search
  end

  # GET /lessons/new
  def new
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def new
  	@user = User.new
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @subjects = Subject.all
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        log_in @user
        flash[:success] = "User was successfully created."
        # redirect_to @user
        format.html { redirect_to @user}
        format.json { render :show, status: :created, location: @user }
      else
        # render 'new'
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
    
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/search_helper.rb
module SearchHelper

	def get_sub_list(subjects)
	  my_courses = current_user().courses		
      if my_courses.length == 0
        return "Not registered for courses"
      end
      str = "<li>#{my_courses[0].name}</li> "
      # puts "*******#{my_courses[0]}"
	  count = 1
      while count < my_courses.length do
      	str+="<li>#{my_courses[count].name}</li>"
        count+=1;
      end
      str.html_safe
  	end

	def get_subject_list(subjects)
	  str = "['Mathematics', 'Mathematics'], ['COSI', 'COSI']"
      str.html_safe
  	end

end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Forgets a persistent session.  
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # Login given user
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns the current logged-in user (if any).
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Course Catalog by Nick April
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Course Catalog", root_url, id: "logo"%>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <%if logged_in?%>
        <li><%= link_to "Home",  current_user %></li>
        <li><%= link_to "Courses",  :controller => :lessons, :action => :index %></li>
        <li><%= link_to "Subjects",  :controller => :subjects, :action => :index %></li>
        <li><%= link_to "Instructors",  :controller => :instructors, :action => :index %></li>
        <li><%= link_to "Search",  search_index_path %></li>

        <li><%= link_to "Log out", logout_path, method: "delete", class: "active" %></li>
       
      <% else %>
        <li><%= link_to "Home",   root_url, class: "active" %></li>
        <li><%= link_to "SignUp", signup_path, class:"glyphicon glyphicon-user" %></li>
        <li><%= link_to "Login", login_path, class: "glyphicon glyphicon-log-in" %></li>
      <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/header' %>
  <div class="container">
    <head>
      <title>Course Catalog</title>

      <%= csrf_meta_tags %>
      <%= action_cable_meta_tag %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    </head>

    <body>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </body>
  </div>
  <%= render 'layouts/footer' %>
</html>

app/views/result/index.html.erb
<h1> Search Results </h1>

<%= link_to 'Back to Search Page', search_index_path %></br >

<% if @lessons.blank? %>
  No Results Found.
<% else %>
  <table>
    <thead>
      <tr>
        <th>Name </th>
        <th>Code</th>
        <th>Independent Study</th>
        <th></th>
        <th>Requirements</th>
        <th colspan="4"></th>
      </tr>
    </thead>
    <tbody>
	  <% @lessons = @lessons.uniq %>
	  <% @lessons.each do |lesson| %>
	    <tr>
	      <td><%= lesson.name %></td>
	      <td><%= lesson.code %></td>
	      <td><%= lesson.independent_study %></td>
	      <td></td>
	      <td><%= lesson.requirements %></td>
	      <% if !Enrollment.where(user_id: current_user.id, lesson_id: lesson.id).exists? %>
		      <td><%= form_for(:enrollments, :url => url_for(:controller => "enrollments", :action => "create", :id => @enrollments)) do |f|%>
		     	<%= f.hidden_field :user_id, value: current_user.id %>
		      	<%= f.hidden_field :lesson_id, value: lesson.id %>
		       	<button type="submit" class="btn btn-primary"> Enroll</button>
	 		  <% end %>
			  </td>
		  <% else %>
			<td> Enrolled </td>
		  <% end %>
	    </tr>
	  <% end %>
	</tbody>
  </table>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_login_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>